package com.casestudy.tg;


import org.springframework.data.annotation.Id;

/***
 * Encapsulates a price entry for a product
 * given its id (called pid)
 * @author AJ Sanchez
 *
 */
public class PriceEntry {
	
	@Id
	private String id; 		// auto generated by MongoDB
	
	private long pid;		// this is the actual internal product id
	private CurrentPrice currentPrice;
	
	public PriceEntry(String mongoID, long id, CurrentPrice currentPrice) {
		super();
		this.id = mongoID;
		this.pid = id;
		this.currentPrice = currentPrice;
	}
	
	public PriceEntry(long id, CurrentPrice currentPrice) {
		super();
		this.pid = id;
		this.currentPrice = currentPrice;
	}

	public PriceEntry(){
		
	}
	
	
	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public long getPid() {
		return pid;
	}

	public void setPid(long pid) {
		this.pid = pid;
	}

	public CurrentPrice getCurrentPrice() {
		return currentPrice;
	}

	public void setCurrentPrice(CurrentPrice currentPrice) {
		this.currentPrice = currentPrice;
	}

	@Override
	public String toString(){
		return "{ id: " + String.valueOf(pid) + ", current_price : { " + currentPrice.toString() + " } }";
	}
}
